name: build
on:
  push:
    branches: [ master ]
    paths-ignore: [ '*.md' ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ '*.md' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          cache: 'gradle'

      - name: Gradle build
        run: ./gradlew build
