name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Gradle build & release
        env:
          PUBLICATION_CREDENTIALS: ${{ secrets.PUBLICATION_CREDENTIALS }}
        run: |
          chmod +x gradlew
          ./gradlew clean checkMavenCentralPublication
          ./gradlew build publish
          ./gradlew closeAndReleaseRepository
